name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi indir
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Android altyapisini olustur
        run: |
          flutter create \
            --platforms=android \
            --org com.animalworldkids \
            --project-name animal_world_jungle_theme \
            /tmp/animal_world_android

          cp -R /tmp/animal_world_android/android ./android

      - name: Paketleri yukle
        run: flutter pub get

      - name: APK olustur
        run: flutter build apk --release

      - name: APK adini degistir
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk \
          build/app/outputs/flutter-apk/Animal_World_Kids_V17_1.apk

      - name: APK dosyasini kaydet
        uses: actions/upload-artifact@v4
        with:
          name: Animal-World-Kids-V17-1-APK
          path: build/app/outputs/flutter-apk/Animal_World_Kids_V17_1.apk
